import { describe, it, expect } from 'vitest';
import { generateTypeScript } from '../generators/typescript.js';
import type { ActionSchema } from '../types.js';

const sampleActions: ActionSchema[] = [
  {
    action: 'getInfo',
    request: {
      title: 'DeviceGetInfoRequest',
      description: 'Request payload for device.getInfo action',
      type: 'object',
      properties: {},
    },
    response: {
      title: 'DeviceGetInfoResponse',
      description: 'Response payload for device.getInfo action',
      type: 'object',
      properties: {
        platform: { type: 'string', description: 'Platform identifier' },
        osVersion: { type: 'string' },
        model: { type: 'string' },
        appVersion: { type: 'string' },
      },
      required: ['platform', 'osVersion', 'model', 'appVersion'],
    },
  },
  {
    action: 'capturePhoto',
    request: {
      title: 'DeviceCapturePhotoRequest',
      type: 'object',
      properties: {
        quality: { type: 'number', description: 'Image quality from 0.0 to 1.0' },
        camera: { type: 'string', enum: ['front', 'back'] },
      },
    },
    response: {
      title: 'DeviceCapturePhotoResponse',
      type: 'object',
      properties: {
        imageBase64: { type: 'string' },
        width: { type: 'integer' },
        height: { type: 'integer' },
      },
      required: ['imageBase64', 'width', 'height'],
    },
  },
];

describe('generateTypeScript', () => {
  it('generates interfaces from schemas', () => {
    const output = generateTypeScript({ moduleName: 'device', actions: sampleActions });

    expect(output).toContain('export interface DeviceGetInfoRequest');
    expect(output).toContain('export interface DeviceGetInfoResponse');
    expect(output).toContain('platform: string;');
    expect(output).toContain('osVersion: string;');
  });

  it('marks optional fields correctly', () => {
    const output = generateTypeScript({ moduleName: 'device', actions: sampleActions });

    expect(output).toContain('quality?: number;');
    expect(output).toContain('camera?: \'front\' | \'back\';');
  });

  it('generates enum union types', () => {
    const output = generateTypeScript({ moduleName: 'device', actions: sampleActions });

    expect(output).toContain("'front' | 'back'");
  });

  it('generates number type for integer', () => {
    const output = generateTypeScript({ moduleName: 'device', actions: sampleActions });

    expect(output).toContain('width: number;');
    expect(output).toContain('height: number;');
  });

  it('includes auto-generated header', () => {
    const output = generateTypeScript({ moduleName: 'device', actions: sampleActions });

    expect(output).toContain('Auto-generated by @rynbridge/codegen');
  });

  it('handles array types', () => {
    const actions: ActionSchema[] = [
      {
        action: 'listDir',
        request: { title: 'ListDirRequest', type: 'object', properties: {} },
        response: {
          title: 'ListDirResponse',
          type: 'object',
          properties: {
            files: { type: 'array', items: { type: 'string' } },
          },
          required: ['files'],
        },
      },
    ];
    const output = generateTypeScript({ moduleName: 'storage', actions });
    expect(output).toContain('files: string[];');
  });
});
