import type { GeneratorOptions, Schema, SchemaProperty } from '../types.js';

export function generateKotlin(options: GeneratorOptions): string {
  const lines: string[] = [
    '// Auto-generated by @rynbridge/codegen — do not edit manually',
    '',
    `package io.rynbridge.${options.moduleName}.generated`,
    '',
  ];

  for (const action of options.actions) {
    lines.push(schemaToDataClass(action.request));
    lines.push('');
    if (action.response) {
      lines.push(schemaToDataClass(action.response));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function schemaToDataClass(schema: Schema): string {
  const lines: string[] = [];
  const required = new Set(schema.required ?? []);
  const entries = Object.entries(schema.properties);

  if (schema.description) {
    lines.push(`/** ${schema.description} */`);
  }

  if (entries.length === 0) {
    lines.push(`data class ${schema.title}(`);
    lines.push('    val _empty: Unit = Unit');
    lines.push(') {');
  } else {
    lines.push(`data class ${schema.title}(`);
    const params: string[] = [];
    for (const [name, prop] of entries) {
      const kotlinType = propToKotlinType(prop);
      const isOptional = !required.has(name);
      const typeStr = isOptional ? `${kotlinType}?` : kotlinType;
      const defaultVal = isOptional ? ' = null' : '';
      const desc = prop.description ? `    /** ${prop.description} */\n` : '';
      params.push(`${desc}    val ${name}: ${typeStr}${defaultVal}`);
    }
    lines.push(params.join(',\n'));
    lines.push(') {');
  }

  // toPayload
  lines.push('    fun toPayload(): Map<String, Any?> {');
  lines.push('        val payload = mutableMapOf<String, Any?>()');
  for (const [name, prop] of entries) {
    const isOptional = !required.has(name);
    if (isOptional) {
      lines.push(`        ${name}?.let { payload["${name}"] = it }`);
    } else {
      lines.push(`        payload["${name}"] = ${name}`);
    }
  }
  lines.push('        return payload');
  lines.push('    }');

  // companion fromPayload
  lines.push('');
  lines.push('    companion object {');
  lines.push(`        fun fromPayload(payload: Map<String, Any?>): ${schema.title} {`);
  lines.push(`            return ${schema.title}(`);
  for (let i = 0; i < entries.length; i++) {
    const [name, prop] = entries[i];
    const kotlinType = propToKotlinType(prop);
    const isOptional = !required.has(name);
    const comma = i < entries.length - 1 ? ',' : '';
    if (isOptional) {
      lines.push(`                ${name} = payload["${name}"] as? ${kotlinType}${comma}`);
    } else {
      lines.push(`                ${name} = payload["${name}"] as ${kotlinType}${comma}`);
    }
  }
  lines.push('            )');
  lines.push('        }');
  lines.push('    }');

  lines.push('}');
  return lines.join('\n');
}

function propToKotlinType(prop: SchemaProperty): string {
  switch (prop.type) {
    case 'string':
      return 'String';
    case 'number':
      return 'Double';
    case 'integer':
      return 'Int';
    case 'boolean':
      return 'Boolean';
    case 'array':
      if (prop.items) {
        return `List<${propToKotlinType(prop.items as SchemaProperty)}>`;
      }
      return 'List<Any>';
    case 'object':
      return 'Map<String, Any?>';
    default:
      return 'Any';
  }
}
