import type { GeneratorOptions, Schema, SchemaProperty } from '../types.js';

export function generateSwift(options: GeneratorOptions): string {
  const lines: string[] = [
    '// Auto-generated by @rynbridge/codegen — do not edit manually',
    '',
    'import Foundation',
    '',
  ];

  for (const action of options.actions) {
    lines.push(schemaToStruct(action.request));
    lines.push('');
    if (action.response) {
      lines.push(schemaToStruct(action.response));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function schemaToStruct(schema: Schema): string {
  const lines: string[] = [];
  const required = new Set(schema.required ?? []);
  const entries = Object.entries(schema.properties);

  if (schema.description) {
    lines.push(`/// ${schema.description}`);
  }
  lines.push(`public struct ${schema.title}: Sendable {`);

  for (const [name, prop] of entries) {
    const swiftType = propToSwiftType(prop);
    const isOptional = !required.has(name);
    const typeStr = isOptional ? `${swiftType}?` : swiftType;
    if (prop.description) {
      lines.push(`    /// ${prop.description}`);
    }
    lines.push(`    public let ${name}: ${typeStr}`);
  }

  // init
  if (entries.length > 0) {
    lines.push('');
    const params = entries.map(([name, prop]) => {
      const swiftType = propToSwiftType(prop);
      const isOptional = !required.has(name);
      const typeStr = isOptional ? `${swiftType}?` : swiftType;
      const defaultVal = isOptional ? ' = nil' : '';
      return `${name}: ${typeStr}${defaultVal}`;
    });
    lines.push(`    public init(${params.join(', ')}) {`);
    for (const [name] of entries) {
      lines.push(`        self.${name} = ${name}`);
    }
    lines.push('    }');
  }

  // toPayload
  lines.push('');
  lines.push('    public func toPayload() -> [String: Any] {');
  lines.push('        var payload: [String: Any] = [:]');
  for (const [name, prop] of entries) {
    const isOptional = !required.has(name);
    if (isOptional) {
      lines.push(`        if let ${name} { payload["${name}"] = ${name} }`);
    } else {
      lines.push(`        payload["${name}"] = ${name}`);
    }
  }
  lines.push('        return payload');
  lines.push('    }');

  // init from payload
  lines.push('');
  lines.push('    public init(from payload: [String: Any]) {');
  for (const [name, prop] of entries) {
    const swiftType = propToSwiftType(prop);
    const isOptional = !required.has(name);
    if (isOptional) {
      lines.push(`        self.${name} = payload["${name}"] as? ${swiftType}`);
    } else {
      lines.push(`        self.${name} = payload["${name}"] as! ${swiftType}`);
    }
  }
  lines.push('    }');

  lines.push('}');
  return lines.join('\n');
}

function propToSwiftType(prop: SchemaProperty): string {
  switch (prop.type) {
    case 'string':
      return 'String';
    case 'number':
      return 'Double';
    case 'integer':
      return 'Int';
    case 'boolean':
      return 'Bool';
    case 'array':
      if (prop.items) {
        return `[${propToSwiftType(prop.items as SchemaProperty)}]`;
      }
      return '[Any]';
    case 'object':
      return '[String: Any]';
    default:
      return 'Any';
  }
}
