import type { GeneratorOptions, Schema, SchemaProperty } from '../types.js';

export function generateTypeScript(options: GeneratorOptions): string {
  const lines: string[] = [
    '// Auto-generated by @rynbridge/codegen — do not edit manually',
    '',
  ];

  for (const action of options.actions) {
    lines.push(schemaToInterface(action.request));
    lines.push('');
    if (action.response) {
      lines.push(schemaToInterface(action.response));
      lines.push('');
    }
  }

  return lines.join('\n');
}

function schemaToInterface(schema: Schema): string {
  const lines: string[] = [];
  if (schema.description) {
    lines.push(`/** ${schema.description} */`);
  }
  lines.push(`export interface ${schema.title} {`);

  const required = new Set(schema.required ?? []);
  const entries = Object.entries(schema.properties);

  for (const [name, prop] of entries) {
    const tsType = propToTsType(prop);
    const optional = !required.has(name) ? '?' : '';
    if (prop.description) {
      lines.push(`  /** ${prop.description} */`);
    }
    lines.push(`  ${name}${optional}: ${tsType};`);
  }

  lines.push('}');
  return lines.join('\n');
}

function propToTsType(prop: SchemaProperty): string {
  if (prop.enum) {
    return prop.enum.map((v) => `'${v}'`).join(' | ');
  }

  const baseType = jsonTypeToTs(prop);

  return baseType;
}

function jsonTypeToTs(prop: SchemaProperty): string {
  switch (prop.type) {
    case 'string':
      return 'string';
    case 'number':
    case 'integer':
      return 'number';
    case 'boolean':
      return 'boolean';
    case 'array':
      if (prop.items) {
        return `${jsonTypeToTs(prop.items as SchemaProperty)}[]`;
      }
      return 'unknown[]';
    case 'object':
      return 'Record<string, unknown>';
    default:
      return 'unknown';
  }
}
